name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # build html
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - run: |
        echo "Hallo"
        pwd
        echo "Hallo"
        ls
        echo "Hallo"
        ls docs/
        echo "Hallo"
        ls docs/docs
    # upload
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/docs/_build/
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: docs/build/html
