name: Sphinx build

on:
  push:
     branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: writ

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build: # vs build?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # python version
    - name: Set python version to 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    # Install dependencies
    - name: Install dependencies
      run: |
          cd docs
          pip install -r requirements.txt
    # Build HTML
    - name: Build HTML
      run: |
          cd docs
          make html
    # upload
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/_build/html/
    # Deploy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
