name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: echo
      run: echo ${GITHUB_WORKSPACE}
    - name: ls
      run: ls -all
    - name: tmp
      run: mkdir /tmp/sphinx-log
    - name: tmp-touch
      run: touch /tmp/sphinx-log
    - name: ls-tmp
      run: ls /tmp -all
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html