name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.2' 
    # build html
    - name: Build HTML
      # uses: ammaraskar/sphinx-action@master
      run: |
          pwd
          echo "HALLO1"
          ls
          echo "HALLO2"
          cd docs
          echo "HALLO3"
          pwd
          echo "HALLO4"
          ls
          echo "HALLO5"
          python --version
          pip install sphinx-needs
          make html
    # upload
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
